(Dashboard) Fix AttributeError in 'complete_ctx' - We handle AttributeError by making sure 'locationsid' is set in 'complete_ctx'.
PHP XMLRPC call: glpi.getAntivirusStatus ()

Python Server traceback:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/mmc/agent.py", line 452, in _putResult
    result = f(*args, **kwargs)
  File "plugins/glpi/__init__.py", line 104, in getAntivirusStatus
    return xmlrpcCleanup(Glpi().getAntivirusStatus(ctx))
  File "/usr/lib/python2.7/dist-packages/mmc/plugins/glpi/database_93.py", line 4747, in getAntivirusStatus
    self.logger.debug("!!!!!!!!!!!!!!!!!!!!!!!!!! %s" % ctx.locations)
exceptions.AttributeError: SecurityContext instance has no attribute 'locations'